### PR TITLE
With setuptools

### PR DESCRIPTION
**Pull request by kba**
Fix shebang and add basic `setup.py`

### CODE REVIEW

**Comment by zuphilip** [comment]
What is the purpose of the non-existing directories in the `.gitignore`?

Feel free to merge when you are ready.

**Comment by kba** [comment]
> What is the purpose of the non-existing directories in the .gitignore?

To prevent git from staging them when they are created.

**Comment by zuphilip** [comment]
<blockquote>To prevent git from staging them when they are created.</blockquote>

Are they created during setup?

**Comment by kba** [comment]
> Are they created during setup?

They are created for setting up virtualenv / building the dist

**Comment by zuphilip** [comment]
Okay. Thanks!

**Pull request merged**
